// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageCluster.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UserOnlineStateMessage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ResponseJoinClusterMessage_JoinResult

typedef GPB_ENUM(ResponseJoinClusterMessage_JoinResult) {
  /** 加入集群成功 */
  ResponseJoinClusterMessage_JoinResult_Success = 1,

  /** 加入集群失败 */
  ResponseJoinClusterMessage_JoinResult_Failure = 2,
};

GPBEnumDescriptor *ResponseJoinClusterMessage_JoinResult_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ResponseJoinClusterMessage_JoinResult_IsValidValue(int32_t value);

#pragma mark - Enum UserOnlineStateMessage_OnlineState

typedef GPB_ENUM(UserOnlineStateMessage_OnlineState) {
  /** 离线 */
  UserOnlineStateMessage_OnlineState_Offline = 2,

  /** 隐身 */
  UserOnlineStateMessage_OnlineState_Invisible = 3,
};

GPBEnumDescriptor *UserOnlineStateMessage_OnlineState_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UserOnlineStateMessage_OnlineState_IsValidValue(int32_t value);

#pragma mark - MessageClusterRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageClusterRoot : GPBRootObject
@end

#pragma mark - RequestJoinClusterMessage

typedef GPB_ENUM(RequestJoinClusterMessage_FieldNumber) {
  RequestJoinClusterMessage_FieldNumber_ServerId = 1,
  RequestJoinClusterMessage_FieldNumber_InvitationCode = 2,
};

/**
 * 请求加入集群消息
 **/
@interface RequestJoinClusterMessage : GPBMessage

/** 服务器ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;
/** Test to see if @c serverId has been set. */
@property(nonatomic, readwrite) BOOL hasServerId;

/** 邀请码，防止第三方服务器加入集群 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *invitationCode;
/** Test to see if @c invitationCode has been set. */
@property(nonatomic, readwrite) BOOL hasInvitationCode;

@end

#pragma mark - ResponseJoinClusterMessage

typedef GPB_ENUM(ResponseJoinClusterMessage_FieldNumber) {
  ResponseJoinClusterMessage_FieldNumber_Result = 1,
};

/**
 * 响应加入集群消息
 **/
@interface ResponseJoinClusterMessage : GPBMessage

@property(nonatomic, readwrite) ResponseJoinClusterMessage_JoinResult result;

@property(nonatomic, readwrite) BOOL hasResult;
@end

#pragma mark - HeartBeatMessage

typedef GPB_ENUM(HeartBeatMessage_FieldNumber) {
  HeartBeatMessage_FieldNumber_ServerId = 1,
  HeartBeatMessage_FieldNumber_Timestamp = 2,
};

/**
 * 心跳包
 **/
@interface HeartBeatMessage : GPBMessage

/** 服务器ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;
/** Test to see if @c serverId has been set. */
@property(nonatomic, readwrite) BOOL hasServerId;

/** 时间戳 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *timestamp;
/** Test to see if @c timestamp has been set. */
@property(nonatomic, readwrite) BOOL hasTimestamp;

@end

#pragma mark - ResponseHeartBeatMessage

typedef GPB_ENUM(ResponseHeartBeatMessage_FieldNumber) {
  ResponseHeartBeatMessage_FieldNumber_Timestamp = 2,
};

/**
 * 响应心跳包
 **/
@interface ResponseHeartBeatMessage : GPBMessage

/** 时间戳 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *timestamp;
/** Test to see if @c timestamp has been set. */
@property(nonatomic, readwrite) BOOL hasTimestamp;

@end

#pragma mark - UserOnlineStateMessage

typedef GPB_ENUM(UserOnlineStateMessage_FieldNumber) {
  UserOnlineStateMessage_FieldNumber_ServerId = 1,
  UserOnlineStateMessage_FieldNumber_UserAccount = 2,
  UserOnlineStateMessage_FieldNumber_UserState = 3,
};

/**
 * 用户在线状态信息
 **/
@interface UserOnlineStateMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;
/** Test to see if @c serverId has been set. */
@property(nonatomic, readwrite) BOOL hasServerId;

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userAccount;
/** Test to see if @c userAccount has been set. */
@property(nonatomic, readwrite) BOOL hasUserAccount;

/** 用户状态 */
@property(nonatomic, readwrite) UserOnlineStateMessage_OnlineState userState;

@property(nonatomic, readwrite) BOOL hasUserState;
@end

#pragma mark - UpdateUserOnlineStateMessage

typedef GPB_ENUM(UpdateUserOnlineStateMessage_FieldNumber) {
  UpdateUserOnlineStateMessage_FieldNumber_ItemCount = 1,
  UpdateUserOnlineStateMessage_FieldNumber_UserOnlineStateArray = 2,
};

/**
 * 更新用户在线状态信息
 **/
@interface UpdateUserOnlineStateMessage : GPBMessage

/** 记录条数 */
@property(nonatomic, readwrite) uint64_t itemCount;

@property(nonatomic, readwrite) BOOL hasItemCount;
/** 用户在线状态 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserOnlineStateMessage*> *userOnlineStateArray;
/** The number of items in @c userOnlineStateArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userOnlineStateArray_Count;

@end

#pragma mark - ServerMessage

typedef GPB_ENUM(ServerMessage_FieldNumber) {
  ServerMessage_FieldNumber_ServerId = 1,
  ServerMessage_FieldNumber_MessageType = 2,
  ServerMessage_FieldNumber_Content = 3,
};

/**
 * 服务器之间的通用消息
 **/
@interface ServerMessage : GPBMessage

/** 服务器ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;
/** Test to see if @c serverId has been set. */
@property(nonatomic, readwrite) BOOL hasServerId;

/** 消息类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageType;
/** Test to see if @c messageType has been set. */
@property(nonatomic, readwrite) BOOL hasMessageType;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

@end

#pragma mark - RequestMessageIDMessage

typedef GPB_ENUM(RequestMessageIDMessage_FieldNumber) {
  RequestMessageIDMessage_FieldNumber_UserAccount = 1,
  RequestMessageIDMessage_FieldNumber_ServerId = 2,
  RequestMessageIDMessage_FieldNumber_RequestId = 3,
};

/**
 * 获取messageID请求
 **/
@interface RequestMessageIDMessage : GPBMessage

/** 用户账号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userAccount;
/** Test to see if @c userAccount has been set. */
@property(nonatomic, readwrite) BOOL hasUserAccount;

/** 服务器ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;
/** Test to see if @c serverId has been set. */
@property(nonatomic, readwrite) BOOL hasServerId;

/** 请求ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *requestId;
/** Test to see if @c requestId has been set. */
@property(nonatomic, readwrite) BOOL hasRequestId;

@end

#pragma mark - ResponseMessageIDMessage

typedef GPB_ENUM(ResponseMessageIDMessage_FieldNumber) {
  ResponseMessageIDMessage_FieldNumber_UserAccount = 1,
  ResponseMessageIDMessage_FieldNumber_MessageId = 2,
  ResponseMessageIDMessage_FieldNumber_ServerId = 3,
  ResponseMessageIDMessage_FieldNumber_RequestId = 4,
};

/**
 * messageID请求的想要
 **/
@interface ResponseMessageIDMessage : GPBMessage

/** 用户账号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userAccount;
/** Test to see if @c userAccount has been set. */
@property(nonatomic, readwrite) BOOL hasUserAccount;

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

/** 服务器ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;
/** Test to see if @c serverId has been set. */
@property(nonatomic, readwrite) BOOL hasServerId;

/** 请求ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *requestId;
/** Test to see if @c requestId has been set. */
@property(nonatomic, readwrite) BOOL hasRequestId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
